### ISSUE TITLE
lua 5.3?

### ISSUE THREAD

**Issue by velkyel** [baguette/lemma#1]
lemma looks interesting.

Are you planning compatibility with lua 5.3?

**Comment by baguette** [comment]
Hey there!

My apologies for taking so long to get back to you on this. For some reason, GitHub did not send me an e-mail notification that this had been posted (or maybe it did, and gmail stuck it somewhere I’d never actually *see* it…), and I’ve spent some time reflecting a bit on where I want to go with Lemma before responding.

**The short answer is:**  Yes, I have tentative plans to add support for Lua 5.2 and 5.3.

**The long answer is:**

I’ve pretty much let this project languish for quite a while, for various reasons. **However**, I’ve lately (i.e., over the last 3-4 months or so) been thinking about resuming development once again. I’ve got the `TODO` list lying around still, and I’ve also thought of quite a few changes and tweaks I’d like to make not only to the compiler and stdlib, but also to the language itself. You may have surmised that the compiler only works properly on Lua 5.1/LuaJIT at the moment, and honestly the last time I really worked on Lemma, 5.3 hadn’t even been released yet…

Well, here are a few of the “biggest” plans that I’ve drawn up for Lemma:

1. Clean-up & redesign some aspects of the language, expand the stdlib, introduce better error detection & handling, support statically “linking” Lemma output (to ease distribution/deployment), flesh-out the documentation, and add some general polish. This phase will introduce several breaking changes to the language and stdlib.
   * Clojure was a big inspiration for me *at first*, but as I kept needing to make different design choices due to the differences between Lua as a runtime and Java as a runtime, a *large* chunk of the stuff I’d imported from Clojure either didn’t make sense anymore, didn’t interoperate well with Lua code, wound up being terribly inefficient, or some combination of those.
   * After some time, Scheme, EuLisp, Le-Lisp, PicoLisp, and Common Lisp wound up having a larger influence on the design, as has Lua itself.
   * I’ve gained a *lot* of experience with various Lisp dialects in the intervening years, and my philosophy of what Lisp *is* (its essence, I suppose) has changed drastically, such that I’m no longer happy with several fundamental aspects of Lemma’s design (and some of the derived aspects, too, but their removal/change won’t have as big of an impact as the fundamental ones `;)`).
   * My sense of aesthetics has also changed considerably as I’ve aged.  C’est la vie.
   * I’ve spent the past year or so designing *another* Lisp dialect (called Evelin, no public release as of yet), and I’m considering transforming Lemma into an implementation of that dialect.  However, I need to figure out how that will affect Lemma’s interop with its host language, how the need for interop might necessitate changes in Evelin, and how best to handle those sorts of issues without compromising on the goals of either language (I do have some ideas, so it’s not a hopeless case).
2. Add support for Lua 5.2 and 5.3.
   * I’m thinking basic support for these will be pretty easy (and quick!) to implement.
   * They’ve also introduced some things which may or may not provide some opportunities for better optimization depending on the target version. Such “advanced support” will likely be neither trivial nor quick, but is on the table.
   * Ideally, I’d like for `lemma`’s compiled output to work without modifications on any (barring, perhaps, the aforementioned optimization settings) of Lua 5.1, 5.2, 5.3, or -JIT (since `lemma` is self-hosting, this also implies that the compiler itself should “just work” as a result of that compatibility;  however, the `lemma` program contains a large portion of raw Lua code, too, which will need to be updated for compat, probably by hand).
   * This probably means that a compatibility library is in order, and, in the interest of keeping Lemma small, performant, and virtually dependency-free (Lua-only for the core language and stdlib), it will probably be a custom compat lib written specifically for `lemma` and its output.
3. Add support for compilation to ECMAScript/JavaScript/JScript/… (henceforth collectively referred to as “JS”).
   * Lua is great, and superior to JS in just about every way.
   * However, as much as I wish Scheme would’ve become UNCOL, I know deep down in my heart of hearts that JS wound up becoming UNCOL.  As such, JS support would expand Lemma’s reach *markedly*:  Web, mobile, Unity, Flash, Cordova, etc.  JS enjoys first-class support on virtually *every* platform (even ones that don’t really matter anymore, like MS-DOS and OS/2), oftentimes out of the box.
   * JS’s semantics are remarkably similar to Lua’s.  They both have first-class functions and a similar default object model.  They have a similar set of base types.  They both tend to use hash tables for everything.  I think Lemma will map nicely onto JS without many, if any, language changes.  A few major differences include the types of values that are admissible as keys in a table/object, and the lack of proper tail-recursion in JS.  These can be worked around if necessary, and otherwise the impedance mismatch is quite low.
   * The Lua target would remain the “reference implementation”, and Lua will still be required when targeting JS.  The ability to leverage a single Lemma codebase to target both Lua and JS without any changes is not a high priority (and creating a node.js-hosted compiler will not be a simple matter of compiling the existing compiler with the JS target, regardless), but with some care, there ought to be considerable overlap — say, perhaps 80-90% of a given codebase *could* be shared for an application that targets both Lua and JS.  I imagine it would be roughly the same as what you’d expect using something like Cordova or Xamarin to target multiple mobile platforms — the “business logic” would be shared, while any UI beyond basic CLI would likely need specific code.  It remains to be seen if close integration with node.js or something like it will be useful or otherwise desirable.

Of course, if you’ve got the skill and the means, contributions are welcome.  Even simple things like suggestions and criticism are invited `:)`

You can also usually find me idling on IRC (Freenode and OFTC, as `groovy2shoes`).  If you’ve got questions/comments more appropriate for chat than Issues, feel free to ping me and/or to join `#lemma` and/or `#evelin` `:)`

One last thought — I’ve been thinking about moving primary development over to [GitLab](https://gitlab.com/baguette/lemma), whereas this repo would become a mere mirror, but I have not decided for sure yet.

**Comment by baguette** [comment]
Fixed in 5c2bd9d.
